// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	request "order-service/internal/modules/room/models/request"

	mock "github.com/stretchr/testify/mock"

	response "order-service/internal/modules/room/models/response"
)

// UsecaseCommand is an autogenerated mock type for the UsecaseCommand type
type UsecaseCommand struct {
	mock.Mock
}

// CreateQueueRoom provides a mock function with given fields: origCtx, payload
func (_m *UsecaseCommand) CreateQueueRoom(origCtx context.Context, payload request.QueueReq) (*response.QueueResp, error) {
	ret := _m.Called(origCtx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueueRoom")
	}

	var r0 *response.QueueResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.QueueReq) (*response.QueueResp, error)); ok {
		return rf(origCtx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.QueueReq) *response.QueueResp); ok {
		r0 = rf(origCtx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.QueueResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.QueueReq) error); ok {
		r1 = rf(origCtx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsecaseCommand creates a new instance of UsecaseCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecaseCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecaseCommand {
	mock := &UsecaseCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
