// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "order-service/internal/modules/order/models/request"

	response "order-service/internal/modules/order/models/response"
)

// UsecaseQuery is an autogenerated mock type for the UsecaseQuery type
type UsecaseQuery struct {
	mock.Mock
}

// FindOrderList provides a mock function with given fields: origCtx, payload
func (_m *UsecaseQuery) FindOrderList(origCtx context.Context, payload request.OrderList) (*response.OrderListResp, error) {
	ret := _m.Called(origCtx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderList")
	}

	var r0 *response.OrderListResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.OrderList) (*response.OrderListResp, error)); ok {
		return rf(origCtx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.OrderList) *response.OrderListResp); ok {
		r0 = rf(origCtx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OrderListResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.OrderList) error); ok {
		r1 = rf(origCtx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPreOrderList provides a mock function with given fields: origCtx, payload
func (_m *UsecaseQuery) FindPreOrderList(origCtx context.Context, payload request.PreOrderList) (*response.PreOrderListResp, error) {
	ret := _m.Called(origCtx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindPreOrderList")
	}

	var r0 *response.PreOrderListResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.PreOrderList) (*response.PreOrderListResp, error)); ok {
		return rf(origCtx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.PreOrderList) *response.PreOrderListResp); ok {
		r0 = rf(origCtx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PreOrderListResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.PreOrderList) error); ok {
		r1 = rf(origCtx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsecaseQuery creates a new instance of UsecaseQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecaseQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecaseQuery {
	mock := &UsecaseQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
